config/routes.rb
Rails.application.routes.draw do
  root "visitors#index"
  get "load-category", to: "visitors#new_products_append", as: "new_products_append"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get "/register", to: "users/registrations#new", as: "new_user" # custom path to sign_up/registration
    post "/register", to: "users/registrations#create", as: "create_user"
    #post '/login' => 'users/sessions#create', :as => :session
  end

  mount Ckeditor::Engine => "/ckeditor"

  resource :user, only: [:show, :update, :edit], path: '/profile'
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :categories, except: [:index] do
    resources :subcategories
  end
  get "browse/categories", to: "categories#index", as: "products_categories"

  resources :reviews, param: :reviewTitle do
    resources :comments
  end
  get "/review/search-products/:name", to: "reviews#search_products", as: "search_review_products"

  resources :products, param: :productTitle do
    member do
      post "like", to: "products#product_like", as: "like"
      post "unlike", to: "products#product_unlike", as: "unlike"
    end
    collection { post :import }
  end
  get "product/:id/buy", to: "products#go_to_aliexpress", as: "aliexpress_pretty_url"
  get "get_subcategories/:category_id", to: "products#get_subcategory"

  # Search products in category
  get "category", to: "search#search_category_redirect", as: "redirect_to_search_in_category" # redirect category
  resources :category_search, controller: :search, path: 'category', param: :name do
    member do
      get "/:p", to: "search#search_category_with_filters", as: "products" # show category
      get "/:subcategory/:p", to: "search#search_category_with_filters", as: "subcategory" # show subcategorycategory
    end
  end

  resource :search do
    get "", to: "search#search_product", as: "redirect_to_products"
    get ":name/:p", action: :search_product, as: "product"
    get "keyword=:keyword", action: :search_keyword, as: "keyword"
    get "author=:author", action: :search_author, as: "author"
  end

  # admins routes
  get "/admins", to: "admins#index", as: :admins
  resource :admins, path: '/admins', only: [] do
    nested do
      scope :aliexpress_api, as: :aliexpress_api do
        # Search for products
        get "search_for_products", to: "admins#search_for_products", as: "products_search"
        post "list_found_products", to: "admins#list_found_products", as: "products_list"
        post "save_approved_products", to: "admins#save_approved_products", as: "products_save"

        # Searching for hot products by category
        get "hot_products_by_category", to: "admins#search_hot_products_by_category", as: "search_hot_products_by_category"
        post "hot_products_by_category", to: "admins#save_hot_products_by_category", as: "save_hot_products_by_category"

        # HACK: something is combined in these routes!
        # Search for all hot products/all not hot products in subcategories
        get "auto_save_hot_products", to: "admins#auto_hot_products", as: "save_hot_products_view"
        post "auto_save_hot_products", to: "admins#auto_hot_products", as: "save_hot_products"
        get "fill_all_subcategories", to: "admins#fill_all_subcategories", as: "fill_all_subcategories"

        # 4 - various clearing
        get "archive_expired_products", to: "admins#archive_expired_products", as: "archive_expired_products"
      end

      scope :scraping, as: :scraping do
        get "update_product_details", to: "admins#update_products_details", as: "update_products_details"
        get "fetch_categories", to: "admins#fetch_categories", as: "fetch_categories"
      end
    end

    get "delete_empty_reviews", to: "admins#delete_empty_reviews", as: "delete_empty_reviews"

    match "comments_manager", to: "admins#comments_manager", as: "comments_manager", via: [:get, :post]

    match "fill_category_from_file", to: "admins#fill_category_from_file", as: "fill_category_from_file", via: [:get, :post]

    # UNDONE: Article manager
    get "article_manage", to: "admins#article_manager", as: "article_manager"
  end

  # Error 404 path
  get "*path", to: "visitors#error404", as: "error" # error 404 page
end

app/views/admins/_form.html.haml
= form_tag admins_aliexpress_api_products_list_path do |f|
  .form-group
    = label :category, "Select category/categories:"
    = select :category, "fields", @categories.collect {|p| [ p.name, p.id ] }, {prompt: "Select Fields", }, {:multiple => true, :size => 10}
  .form-group
    = label :keyword, "Keywords to find, spearate by comma:"
    = text_field_tag :keyword, '', placeholder: 'eg. Xiaomi MI8'
  .form-group
    = label :sort, "Sort by:"
    = check_box :sort, "commissionRateUp" ""
    %label{:for => "sort_commissionRateUp"} Commision Rate Up
  .form-group
    = label :hot_products, "Only hot products?"
    = check_box :hot_products, "yes" "no"
    %label{:for => "hot_products_yesno"} Hot
  .form-group
    = label :min_seller_rating, "Min seller rating:"
    %input#min_seller_rating{:max => "5000", :min => "0", :name => "min_seller_rating", :oninput => "minsellerRating()", :step => "25", :type => "range", :value => "0"}/
    %p#min_rating 0
  .form-group
    = label :min_seller_rating, "Max seller rating:"
    %input#max_seller_rating{:max => "5000", :min => "0", :name => "max_seller_rating", :oninput => "maxsellerRating()", :step => "25", :type => "range", :value => "5000"}/
    %p#max_rating 5000
  .form-group
    = button_tag 'Submit', type: 'submit'

:javascript
  function minsellerRating() {
    a = document.getElementById("min_seller_rating").value
    document.getElementById("min_rating").innerHTML = a
  }
  function maxsellerRating() {
    a = document.getElementById("max_seller_rating").value
    document.getElementById("max_rating").innerHTML = a
  }

app/views/admins/_navigation.html.haml
.row
  .col-md-12
    = link_to "Administration Panel", admins_path
    \---&gt; Current Page

app/views/admins/article_manager.html.haml
=# Update this file or delete it!

app/views/admins/auto_hot_products.html.haml
Are you sure you want to do this action? It will take about 20 minutes!
%input{:onclick => "send()", :type => "submit"}/
#result 
  %marquee Wait! Text will stop moving after all!

:javascript
  function send() {
    $.ajax({
      type: "POST",
      url: "#{admins_aliexpress_api_save_hot_products_path}" ,
      success: function(data){
       $('#result').text("Done");
       alert("We have found new products!")
      }
    });
  }

app/views/admins/clear_expired_items.html.haml
We are selecting are expired products now!

app/views/admins/comments_manager.html.haml
.row
  = form_tag comments_manager_admins_path, method: :post do |f|
    .form-group
      = label :api_call, "Update Comments"
      = button_tag 'Submit', type: 'submit', :class => "btn btn-small btn-success"
    - $i = 0
    - @unapproved_comments.each do |comment|
      .col-md-12
        .col-md-1= User.find(comment.author).nickname
        .col-md-1
          - $review = Review.where(:id => comment.page).first
          - if $review.nil?
            Page Delete
          - else
            = link_to $review.title, review_path($review.title)
        .col-md-1= comment.created_at
        .col-md-9= comment.content
        -# TODO: You can use form partial from comments category
        Approve Comment #{radio_button_tag "commentId[#{$i}]", "#{comment.id}a", false, :class => "approved"}
        Disapprove #{radio_button_tag "commentId[#{$i}]", "#{comment.id}n", true, :class => "disapproved"}
        Delete #{radio_button_tag "commentId[#{$i}]", "#{comment.id}d", false, :class => "deleted"}
        - $i += 1

app/views/admins/fetch_categories.html.haml
- @page.css(".item.util-clearfix").each do |category|
  = category.css(".big-title").css('a').text
  = category.css('a').to_s.split("/")[4]

app/views/admins/fill_category_from_file.html.haml
= form_tag fill_category_from_file_admins_path, action: :upload, multipart: true, method: :post do |f|
  .form-group
    = label :category, "Which category do you want to fill?"
    = select :category, "fields", Category.all.collect {|p| [ p.name, p.id ] }, {prompt: "Select Fields"}, {:multiple => true, :size => 10}
  .form-group
    = label :keywords, "Upload list of comma separated keywords"
    = file_field :keywords, "fields"
  .form-group
    = button_tag 'Submit', type: 'submit'

app/views/admins/hot_products.html.haml
= form_tag api_save_hot_products_path do |f|
  = @config
  .form-group
    = label :fields, "Which language do you want to choose? (EN by default)"
    = select :language, "fields", ['en','pt','ru','es','fr','id','it','nl','tr','vi','th','de','ko','ja','ar','pl','he'], {prompt: "Select Fields"}
  .form-group
    = label :fields, "Which currency do you want to use? (USD by default)"
    = select :currency, "fields", ['USD', 'RUB', 'GBP', 'BRL', 'CAD', 'AUD', 'EUR', 'INR', 'UAH', 'JPY', 'MXN', 'IDR', 'TRY', 'SEK', 'PLN'], {prompt: "Select Fields"}
  .form-group
    = label :category, "Which category do you want to search?"
    = select :category, "fields", Category.all.collect {|p| [ p.name, p.id ] }, {prompt: "Select Fields"}, {:multiple => true, :size => 10}
  .form-group
    = label :api_call, "Submit"
    = button_tag 'Submit', type: 'submit'

app/views/admins/hot_products_by_category.html.haml
= form_tag api_save_hot_products_by_category_path do |f|
  = @config
  .form-group
    = label :fields, "Which language do you want to choose? (EN by default)"
    = select :language, "fields", ['en','pt','ru','es','fr','id','it','nl','tr','vi','th','de','ko','ja','ar','pl','he'], {prompt: "Select Fields"}
  .form-group
    = label :fields, "Which currency do you want to use? (USD by default)"
    = select :currency, "fields", ['USD', 'RUB', 'GBP', 'BRL', 'CAD', 'AUD', 'EUR', 'INR', 'UAH', 'JPY', 'MXN', 'IDR', 'TRY', 'SEK', 'PLN'], {prompt: "Select Fields"}
  .form-group
    = label :category, "Which category do you want to search?"
    = select :category, "fields", Category.all.collect {|p| [ p.name, p.id ] }, {prompt: "Select Fields"}, {:multiple => true, :size => 10}
  .form-group
    = label :api_call, "Submit"
    = button_tag 'Submit', type: 'submit'

app/views/admins/index.html.haml
.row
  .col-md-12.text-center
    %h2
      Welcome to AliBestDeal.com Admin Panel v0.1
  .col-md-12
    .col-lg-2.col-md-4.col-sm-6.col-xs-12
      .process
        .process-row
          .process-step
            = link_to admins_aliexpress_api_products_search_path, class: "btn btn-default btn-circle category-listing-link" do
              =icon('fa', 'underline fa-3x')
            %p Search by Keywords
    .col-lg-2.col-md-4.col-sm-6.col-xs-12
      .process
        .process-row
          .process-step
            = link_to admins_aliexpress_api_search_hot_products_by_category_path, class: "btn btn-default btn-circle category-listing-link" do
              = icon('fa', 'fire fa-3x')
            %p Hot Products by Category
    .col-lg-2.col-md-4.col-sm-6.col-xs-12
      .process
        .process-row
          .process-step
            = link_to admins_aliexpress_api_save_hot_products_view_path, class: "btn btn-default btn-circle category-listing-link" do
              = icon('fa', 'fire-extinguisher fa-3x')
            %p
              Add Products from Hot List
              %b 20 MINUTES OR MORE
    .col-lg-2.col-md-4.col-sm-6.col-xs-12
      .process
        .process-row
          .process-step
            = link_to admins_aliexpress_api_archive_expired_products_path, class: "btn btn-default btn-circle category-listing-link" do
              = icon('fa', 'calendar-times-o fa-3x')
            %p Check for outdated products
    .col-lg-2.col-md-4.col-sm-6.col-xs-12
      .process
        .process-row
          .process-step
            = link_to article_manager_admins_path, class: "btn btn-default btn-circle category-listing-link" do
              = icon('fa', 'list-alt fa-3x')
            %p Manage articles
    .col-lg-2.col-md-4.col-sm-6.col-xs-12
      .process
        .process-row
          .process-step
            = link_to comments_manager_admins_path, class: "btn btn-default btn-circle category-listing-link" do
              = icon('fa', 'comment fa-3x')
            %p Comments managre
  .col-lg-2.col-md-4.col-sm-6.col-xs-12
    .process
      .process-row
        .process-step
          = link_to fill_category_from_file_admins_path, class: "btn btn-default btn-circle category-listing-link" do
            = icon('fa', 'file fa-3x')
          %p Fill Category From File
  .col-lg-2.col-md-4.col-sm-6.col-xs-12
    .process
      .process-row
        .process-step
          = link_to admins_aliexpress_api_fill_all_subcategories_path, class: "btn btn-default btn-circle category-listing-link" do
            = icon('fa', 'bomb fa-3x')
          %p Mass Subcategory Filling
  .col-lg-2.col-md-4.col-sm-6.col-xs-12
    .process
      .process-row
        .process-step
          = link_to admins_scraping_update_products_details_path, class: "btn btn-default btn-circle category-listing-link" do
            = icon('fa', 'chrome fa-3x')
          %p Update Products Details
  .col-lg-2.col-md-4.col-sm-6.col-xs-12
    .process
      .process-row
        .process-step
          = link_to delete_empty_reviews_admins_path, class: "btn btn-default btn-circle category-listing-link" do
            = icon('fa', 'trash fa-3x')
          %p Delete empty reviews

app/views/admins/list_found_products.html.haml
- if @products.size.zero?
  Sorry, we have found nothing :( #{admins_aliexpress_api_search_hot_products_by_category_path}
- else
  Success, we have found #{@products.size} products!
  = form_tag admins_aliexpress_api_products_save_path  do |f|
    .form-group
      = label :api_call, "Api Call Method"
      = button_tag 'Submit', type: 'submit'
    %table
      %tr
        %td productTitle
        %td Image
        %td salePrice
        = succeed ">" do
          %td discount
        %td validTime
        %td Approved?
        %td= link_to "Approve All", "#", :id => "approve_all", :remote => true
        %td= link_to "Disapprove All", "#", :id => "disapprove_all", :remote => true
      - @products["result"]["products"].each do |product|
        %tr
          %td= simple_format(product["productTitle"])
          %td= image_tag product["imageUrl"], {width: "250px", height: "250px"}
          %td
            %b= product["salePrice"]
          %td= product["discount"]
          %td= product["validTime"]
          %td
            = label :approved, "Accept?"
            = check_box_tag "productId[]", product["productId"], 0, :class => "checkboxes"
      %tr
        %td{colspan: 6}
        %td= link_to "Approve All", "#", id: "approve_all", remote: true
        %td= link_to "Disapprove All", "#", id: "disapprove_all", remote: true
    .form-group
      = label :api_call, "Api Call Method"
      = button_tag 'Submit', type: 'submit'
    
:javascript
  $(document).ready(function () {
    $('#approve_all').click(function (){
      $(".checkboxes").each( function () {
        $(this).prop('checked', true);
        });
    });
    $('#disapprove_all').click(function (){
      $(".checkboxes").each( function () {
        $(this).prop('checked', false);
        });
    });
  });

app/views/admins/partial_wraper.html.haml
= render "navigation"

app/views/admins/search_for_products.html.haml
= link_to "Admin Panel", admins_path
= render "form"