config/routes.rb
Rails.application.routes.draw do
  root "visitors#index"
  get "load-category", to: "visitors#new_products_append", as: "new_products_append"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get "/register", to: "users/registrations#new", as: "new_user" # custom path to sign_up/registration
    post "/register", to: "users/registrations#create", as: "create_user"
    #post '/login' => 'users/sessions#create', :as => :session
  end

  mount Ckeditor::Engine => "/ckeditor"

  resource :user, only: [:show, :update, :edit], path: '/profile'
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :categories, except: [:index] do
    resources :subcategories
  end
  get "browse/categories", to: "categories#index", as: "products_categories"

  resources :reviews, param: :reviewTitle do
    resources :comments
  end
  get "/review/search-products/:name", to: "reviews#search_products", as: "search_review_products"

  resources :products, param: :productTitle do
    member do
      post "like", to: "products#product_like", as: "like"
      post "unlike", to: "products#product_unlike", as: "unlike"
    end
    collection { post :import }
  end
  get "product/:id/buy", to: "products#go_to_aliexpress", as: "aliexpress_pretty_url"
  get "get_subcategories/:category_id", to: "products#get_subcategory"

  # Search products in category
  get "category", to: "search#search_category_redirect", as: "redirect_to_search_in_category" # redirect category
  resources :category_search, controller: :search, path: 'category', param: :name do
    member do
      get "/:p", to: "search#search_category_with_filters", as: "products" # show category
      get "/:subcategory/:p", to: "search#search_category_with_filters", as: "subcategory" # show subcategorycategory
    end
  end

  resource :search do
    get "", to: "search#search_product", as: "redirect_to_products"
    get ":name/:p", action: :search_product, as: "product"
    get "keyword=:keyword", action: :search_keyword, as: "keyword"
    get "author=:author", action: :search_author, as: "author"
  end

  # admins routes
  get "/admins", to: "admins#index", as: :admins
  resource :admins, path: '/admins', only: [] do
    nested do
      scope :aliexpress_api, as: :aliexpress_api do
        # Search for products
        get "search_for_products", to: "admins#search_for_products", as: "products_search"
        post "list_found_products", to: "admins#list_found_products", as: "products_list"
        post "save_approved_products", to: "admins#save_approved_products", as: "products_save"

        # Searching for hot products by category
        get "hot_products_by_category", to: "admins#search_hot_products_by_category", as: "search_hot_products_by_category"
        post "hot_products_by_category", to: "admins#save_hot_products_by_category", as: "save_hot_products_by_category"

        # HACK: something is combined in these routes!
        # Search for all hot products/all not hot products in subcategories
        get "auto_save_hot_products", to: "admins#auto_hot_products", as: "save_hot_products_view"
        post "auto_save_hot_products", to: "admins#auto_hot_products", as: "save_hot_products"
        get "fill_all_subcategories", to: "admins#fill_all_subcategories", as: "fill_all_subcategories"

        # 4 - various clearing
        get "archive_expired_products", to: "admins#archive_expired_products", as: "archive_expired_products"
      end

      scope :scraping, as: :scraping do
        get "update_product_details", to: "admins#update_products_details", as: "update_products_details"
        get "fetch_categories", to: "admins#fetch_categories", as: "fetch_categories"
      end
    end

    get "delete_empty_reviews", to: "admins#delete_empty_reviews", as: "delete_empty_reviews"

    match "comments_manager", to: "admins#comments_manager", as: "comments_manager", via: [:get, :post]

    match "fill_category_from_file", to: "admins#fill_category_from_file", as: "fill_category_from_file", via: [:get, :post]

    # UNDONE: Article manager
    get "article_manage", to: "admins#article_manager", as: "article_manager"
  end

  # Error 404 path
  get "*path", to: "visitors#error404", as: "error" # error 404 page
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @recent_reviews = Review.limit(3).order("id desc")
    @categories = Category.limit(8).sample(1)
    @best_products = Product.where(is_hot: 'y').limit(32).sample(16)
    session[:excluded_categories] = []

    # META
    set_meta_tags title: "Aliexpress Best Deals"
    set_meta_tags description: "Here you can find new hot products from AliExpress with reviews and user feedback! Buy smarter with us!"
    set_meta_tags keywords: "aliexpress,deal,review,shipping,how to buy,faq,prices,products,deals,find,review,test"
  end

  def hot_products; end

  def new_products_append
    @categories = Category.where.not(id: session[:excluded_categories]).sample(2)
    respond_to do |format|
      format.js
    end
  end

  def error404
    # META
    set_meta_tags title: "404 Page not found!"
    set_meta_tags description: "This page doesnt exist! But you may back to our home page and discover our website!"
    set_meta_tags keywords: "aliexpress,deal,review,error,page,404"
  end
end

app/views/visitors/_all_products.html.haml
- @categories ||= categories
#all-items
  .container
    - if @categories.nil?
      %h2{:style => "text-transform:uppercase;"}
        There is no more categories to show  - #{link_to "More products", products_path, style: "color:blue;"}
    - else
      - @categories.each do |category|
        - session[:excluded_categories] << category.id
        - next if category.products.count < 4
        %h1
          %i{:class => "#{category.icon}"}
          = link_to category.name, products_category_search_path(category.name, 1)
        - category.products.limit(64).sample(8).in_groups_of(8, false).each do |big_product_group|
          .row
            - big_product_group.each_slice(4).to_a.each do |small_product_group|
              .one-item.col-md-3.col-sm-3.col-xs-12
                .item-sp.item-lg
                  %span{:itemscope => "", :itemtype => "http://schema.org/Product"}
                    = link_to product_path(pretty_url_encode(small_product_group[0].productTitle)), itemprop: "url" do
                      .thumb.vertical-alignment-helper
                        .vertical-align-center.vertical-align-top
                          = image_tag "#{small_product_group[0].imageUrl}_350x350.jpg", class: "img-responsive"
                      %h4{:itemprop => "name"}
                        = simple_format(pretty_url_decode(small_product_group[0].productTitle))
                      .price{:itemprop => "offers", :itemscope => "", :itemtype => "http://schema.org/Offer"}
                        %meta{:content => "#{small_product_group[0].salePrice}", :itemprop => "price"}/
                        %meta{:content => "USD", :itemprop => "priceCurrency"}/
                        %span.small NOW ONLY:
                        %span.big
                          US #{small_product_group[0].salePrice}$
              .three-item.col-md-3.col-sm-3.col-xs-12
                - small_product_group[1..3].each do |product|
                  .item-sp.item-sm
                    %span{:itemscope => "", :itemtype => "http://schema.org/Product"}
                      = link_to product_path(pretty_url_encode(product.productTitle)), itemprop: "url" do
                        .thumb.vertical-alignment-helper
                          .vertical-align-center.vertical-align-top
                            = image_tag "#{product.imageUrl}_350x350.jpg", class: "img-responsive"
                        %h4{:itemprop => "name"}
                          = simple_format(pretty_url_decode(product.productTitle))
                        .price{:itemprop => "offers", :itemscope => "", :itemtype => "http://schema.org/Offer"}
                          %meta{:content => "#{product.salePrice}", :itemprop => "price"}/
                          %meta{:content => "USD", :itemprop => "priceCurrency"}/
                          %span.small NOW ONLY:
                          %span.big
                            US #{product.salePrice}$
        %hr{:style => "background-color:#{random_colors};height:5px;border-radius:5px 5px 5px 5px;"}
  - if !@categories.nil?
    .rounded-plus-container
      = link_to new_products_append_path, remote: true, style: "width:180px;height:180px;", class: "add-categories" do
        .rounded-plus
          = icon('fa', 'plus fa-5x')


:javascript
  $(function() {
    $('.add-categories').click(function() {
      $('.rounded-plus-container').fadeOut(200);
    });
  });

app/views/visitors/_recent_reviews.html.haml
.container
  .row
    .col-md-12.text-center.fade-in-b.recent-reviews
      %h1 Recent AliExpress reviews:
  .row.recent-reviews-container{:style => "background-color:#f8f8f8;"}
    - $js = 1
    - @recent_reviews.each do |review|
      .col-md-4
        .card
          .card-image
            = link_to review_url(pretty_url_encode(review.title)) do
              = image_tag review.cover.url, :class => "img-responsive"
          .card-content
            %span.card-title= pretty_url_decode(review.title)
            %button.btn.btn-custom.pull-right{"aria-label" => "Left Align", :id => "show#{$js}", :type => "button"}
              = icon('fa','ellipsis-v')
          .card-action
            - review.keywords.split(",").each do |keyword|
              = link_to keyword, keyword_search_path(keyword)
          %div{:class => "card-reveal #{$js}"}
            %span.card-title= pretty_url_decode(review.title)
            %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
              %span{"aria-hidden" => "true"} ×
            %p= review.short_description
            = link_to "Read More", review_url(pretty_url_encode(review.title)), class: "btn btn-success"
      - $js +=  1
  .row.more-reviews
    = link_to "Read other products reviews", reviews_path
    
:javascript
  $(function(){
      $('#show1').on('click',function(){        
          $('.card-reveal.1').slideToggle('slow');
      });
      $('.card-reveal.1 .close').on('click',function(){
          $('.card-reveal.1').slideToggle('slow');
      });
  });
  $(function(){
      $('#show2').on('click',function(){        
          $('.card-reveal.2').slideToggle('slow');
      });
      $('.card-reveal.2 .close').on('click',function(){
          $('.card-reveal.2').slideToggle('slow');
      });
  });
  $(function(){
    $('#show3').on('click',function(){        
      $('.card-reveal.3').slideToggle('slow');
    });
    $('.card-reveal.3 .close').on('click',function(){
      $('.card-reveal.3').slideToggle('slow');
    });
  });

app/views/visitors/_slider.html.haml
.visitors-slider
  #bs-carousel.carousel.fade-carousel.slide{"data-interval" => "20000", "data-ride" => "carousel"}
    %ol.carousel-indicators
      %li.active{"data-slide-to" => "0", "data-target" => "#bs-carousel"}
      %li{"data-slide-to" => "1", "data-target" => "#bs-carousel"}
      %li{"data-slide-to" => "2", "data-target" => "#bs-carousel"}
    .carousel-inner
      .item.slides.active
        .slide-1
        .hero
          %hgroup
            %h1 Alibestdeal?
            %h3 Find top quality Aliexpress products
          = link_to products_path do
            %button.btn.btn-danger.btn-lg See All Products
      .item.slides
        .slide-2
        .hero
          %hgroup
            %h1 We are smart
            %h3.smaller
              Read reviews of many Aliexpress products
              = succeed "Stop" do
                %br
          = link_to reviews_path do
            %button.btn.btn-warning.btn-lg Read Reviews
      .item.slides
        .slide-3
        .hero
          %hgroup
            %h1 We are community
            %h3 Like and comment your favorite products
          = link_to new_user_path do
            %button.btn.btn-success.btn-lg Start Now!

:javascript
  $('.carousel').carousel({
    interval: 1000 * 12
  });

app/views/visitors/error404.html.haml
.error
  .error-code.m-b-10.m-t-20
    404
    = icon('fa', 'warning')
  %h3.font-bold We couldn't find the page..
  .error-desc
    Sorry, but the page you are looking for was either not found or does not exist.
    %br/
    Try refreshing the page or click the button below to go back to the Homepage.
    %div
      = link_to root_path, class: "login-detail-panel-button btn" do
        = icon('fa', 'arrow-left')
        Go back to Homepage

app/views/visitors/index.html.haml
= render "slider"
= render "recent_reviews"
= render "/layouts/ad"
= render "/products/best_products", products: @best_products
%hr{:style => "height:5px;background-color:#2ecc71;border-radius:5px 5px 5px 5px;"}/
%h2{:style => "text-transform:uppercase;"} Find awesome products between many categories:
= render "all_products"

app/views/visitors/new_products_append.js.haml
$('#all-items').append('#{escape_javascript(render "visitors/all_products", categories: @categories)}').fadeIn(2000);