config/routes.rb
Rails.application.routes.draw do
  root "visitors#index"
  get "load-category", to: "visitors#new_products_append", as: "new_products_append"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get "/register", to: "users/registrations#new", as: "new_user" # custom path to sign_up/registration
    post "/register", to: "users/registrations#create", as: "create_user"
    #post '/login' => 'users/sessions#create', :as => :session
  end

  mount Ckeditor::Engine => "/ckeditor"

  resource :user, only: [:show, :update, :edit], path: '/profile'
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :categories, except: [:index] do
    resources :subcategories
  end
  get "browse/categories", to: "categories#index", as: "products_categories"

  resources :reviews, param: :reviewTitle do
    resources :comments
  end
  get "/review/search-products/:name", to: "reviews#search_products", as: "search_review_products"

  resources :products, param: :productTitle do
    member do
      post "like", to: "products#product_like", as: "like"
      post "unlike", to: "products#product_unlike", as: "unlike"
    end
    collection { post :import }
  end
  get "product/:id/buy", to: "products#go_to_aliexpress", as: "aliexpress_pretty_url"
  get "get_subcategories/:category_id", to: "products#get_subcategory"

  # Search products in category
  get "category", to: "search#search_category_redirect", as: "redirect_to_search_in_category" # redirect category
  resources :category_search, controller: :search, path: 'category', param: :name do
    member do
      get "/:p", to: "search#search_category_with_filters", as: "products" # show category
      get "/:subcategory/:p", to: "search#search_category_with_filters", as: "subcategory" # show subcategorycategory
    end
  end

  resource :search do
    get "", to: "search#search_product", as: "redirect_to_products"
    get ":name/:p", action: :search_product, as: "product"
    get "keyword=:keyword", action: :search_keyword, as: "keyword"
    get "author=:author", action: :search_author, as: "author"
  end

  # admins routes
  get "/admins", to: "admins#index", as: :admins
  resource :admins, path: '/admins', only: [] do
    nested do
      scope :aliexpress_api, as: :aliexpress_api do
        # Search for products
        get "search_for_products", to: "admins#search_for_products", as: "products_search"
        post "list_found_products", to: "admins#list_found_products", as: "products_list"
        post "save_approved_products", to: "admins#save_approved_products", as: "products_save"

        # Searching for hot products by category
        get "hot_products_by_category", to: "admins#search_hot_products_by_category", as: "search_hot_products_by_category"
        post "hot_products_by_category", to: "admins#save_hot_products_by_category", as: "save_hot_products_by_category"

        # HACK: something is combined in these routes!
        # Search for all hot products/all not hot products in subcategories
        get "auto_save_hot_products", to: "admins#auto_hot_products", as: "save_hot_products_view"
        post "auto_save_hot_products", to: "admins#auto_hot_products", as: "save_hot_products"
        get "fill_all_subcategories", to: "admins#fill_all_subcategories", as: "fill_all_subcategories"

        # 4 - various clearing
        get "archive_expired_products", to: "admins#archive_expired_products", as: "archive_expired_products"
      end

      scope :scraping, as: :scraping do
        get "update_product_details", to: "admins#update_products_details", as: "update_products_details"
        get "fetch_categories", to: "admins#fetch_categories", as: "fetch_categories"
      end
    end

    get "delete_empty_reviews", to: "admins#delete_empty_reviews", as: "delete_empty_reviews"

    match "comments_manager", to: "admins#comments_manager", as: "comments_manager", via: [:get, :post]

    match "fill_category_from_file", to: "admins#fill_category_from_file", as: "fill_category_from_file", via: [:get, :post]

    # UNDONE: Article manager
    get "article_manage", to: "admins#article_manager", as: "article_manager"
  end

  # Error 404 path
  get "*path", to: "visitors#error404", as: "error" # error 404 page
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :subcategories
  has_many :products, through: :subcategories

  def save_fetched_categories_and_subcategories
    page.css(".item.util-clearfix").each do |category|
      category_name = category.css(".big-title").css("a").text
      category_id = category.css("a").to_s.split("/")[4]
      category.css(".sub-item-cont").css("a").each do |subcategory|
        subcategory_name = subcategory.text
        subcategory_id = subcategory.to_s.split("/")[4]
        Subcategory.create(category_id: @category_id, name: subcategory_name, id: subcategory_id) if Subcategory.find(subcategory_id).nil?
      end
      Category.create(id: category_id, name: category_name) if Category.find(category_id).nil?
    end
  end

  def self.fill_from_file(keywords, category)
    keywords.each do |keyword|
      AliexpressScraper.search_for_category_products(keyword, category)
      Product.save_hot_products(@products["result"]["products"], category)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :is_admin?, only: [:update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_all_products_in_category.html.haml
- if @products.nil?
  %h2 Nothing found!
  = render "products/search_box"
- else
  #all-items
    .container
      .col-md-12
        - @products[32*(params[:p].to_i-1)...32*params[:p].to_i].in_groups_of(8,false).each do |big_product_group|
          .row
            - big_product_group.each_slice(4).to_a.each do |small_product_group|
              .one-item.col-md-3.col-sm-3.col-xs-12
                .item-sp.item-lg
                  %span{:itemscope => "", :itemtype => "http://schema.org/Product"}
                    = link_to product_path(pretty_url_encode(small_product_group[0].productTitle)), itemprop: "url" do
                      .thumb.vertical-alignment-helper
                        .vertical-align-center.vertical-align-top
                        = image_tag "#{small_product_group[0].imageUrl}_350x350.jpg", class: "img-responsive"
                      %h4{:itemprop => "name"}
                        = simple_format(pretty_url_decode(small_product_group[0].productTitle))
                      .price{:itemprop => "offers", :itemscope => "", :itemtype => "http://schema.org/Offer"}
                        %meta{:content => "#{small_product_group[0].salePrice}", :itemprop => "price"}/
                        %meta{:content => "USD", :itemprop => "priceCurrency"}/
                        %span.small NOW ONLY:
                        %span.big
                          US #{small_product_group[0].salePrice}$
                          - if !current_user.nil?
                            - if current_user.is_admin = "y"
                              = link_to "Delete It", product_path(pretty_url_encode(small_product_group[0].productTitle)), method: :delete, target: "_blank"
              .three-item.col-md-3.col-sm-3.col-xs-12
                - small_product_group[1..3].each do |product|
                  .item-sp.item-sm
                    %span{:itemscope => "", :itemtype => "http://schema.org/Product"}
                      = link_to product_path(pretty_url_encode(product.productTitle)), itemprop: "url" do
                        .thumb.vertical-alignment-helper
                          .vertical-align-center.vertical-align-top
                            = image_tag "#{product.imageUrl}_350x350.jpg", class: "img-responsive"
                        %h4{:itemprop => "name"}
                          = simple_format(pretty_url_decode(product.productTitle))
                        .price{:itemprop => "offers", :itemscope => "", :itemtype => "http://schema.org/Offer"}
                          %meta{:content => "#{product.salePrice}", :itemprop => "price"}/
                          %meta{:content => "USD", :itemprop => "priceCurrency"}/
                          %span.small NOW ONLY:
                          %span.big
                            US #{product.salePrice}$
                          - if !current_user.nil?
                            - if current_user.is_admin = "y"
                              = link_to "Delete It", product_path(pretty_url_encode(product.productTitle)), method: :delete, target: "_blank"
      = render "search/pagination"
      = render "search/search_box"

app/views/categories/_form.html.haml
= form_for(@category, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @category.errors.any?
    .alert.alert-danger.alert-dismissable{:role => "alert"}
      %button.close{"data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
        %span.sr-only Close
      %h4
        = pluralize(@category.errors.count, "error")
        prohibited this category from being saved:
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :name, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/categories/_listing.html.haml
.container
  .row
    %h2 Find products by category:
    .col-md-12
      - @categories.each do |category|
        .col-lg-2.col-md-4.col-sm-6.col-xs-12
          .process
            .process-row
              .process-step
                = link_to products_category_search_path(category.name,1), class: "btn btn-default btn-circle category-listing-link" do
                  =icon('fa', "#{category.icon} fa-3x")
                %p= category.name

app/views/categories/edit.html.haml
.page-header
  = link_to categories_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @category, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing category
= render 'form'

app/views/categories/index.html.haml
= render "search/search_box"
= render "listing"

app/views/categories/new.html.haml
.page-header
  = link_to categories_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New category
= render 'form'

app/views/categories/show.html.haml
.page-header
  = link_to categories_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_category_path(@category), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show category
%dl.dl-horizontal
  %dt Name:
  %dd= @category.name