config/routes.rb
Rails.application.routes.draw do
  root "visitors#index"
  get "load-category", to: "visitors#new_products_append", as: "new_products_append"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get "/register", to: "users/registrations#new", as: "new_user" # custom path to sign_up/registration
    post "/register", to: "users/registrations#create", as: "create_user"
    #post '/login' => 'users/sessions#create', :as => :session
  end

  mount Ckeditor::Engine => "/ckeditor"

  resource :user, only: [:show, :update, :edit], path: '/profile'
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :categories, except: [:index] do
    resources :subcategories
  end
  get "browse/categories", to: "categories#index", as: "products_categories"

  resources :reviews, param: :reviewTitle do
    resources :comments
  end
  get "/review/search-products/:name", to: "reviews#search_products", as: "search_review_products"

  resources :products, param: :productTitle do
    member do
      post "like", to: "products#product_like", as: "like"
      post "unlike", to: "products#product_unlike", as: "unlike"
    end
    collection { post :import }
  end
  get "product/:id/buy", to: "products#go_to_aliexpress", as: "aliexpress_pretty_url"
  get "get_subcategories/:category_id", to: "products#get_subcategory"

  # Search products in category
  get "category", to: "search#search_category_redirect", as: "redirect_to_search_in_category" # redirect category
  resources :category_search, controller: :search, path: 'category', param: :name do
    member do
      get "/:p", to: "search#search_category_with_filters", as: "products" # show category
      get "/:subcategory/:p", to: "search#search_category_with_filters", as: "subcategory" # show subcategorycategory
    end
  end

  resource :search do
    get "", to: "search#search_product", as: "redirect_to_products"
    get ":name/:p", action: :search_product, as: "product"
    get "keyword=:keyword", action: :search_keyword, as: "keyword"
    get "author=:author", action: :search_author, as: "author"
  end

  # admins routes
  get "/admins", to: "admins#index", as: :admins
  resource :admins, path: '/admins', only: [] do
    nested do
      scope :aliexpress_api, as: :aliexpress_api do
        # Search for products
        get "search_for_products", to: "admins#search_for_products", as: "products_search"
        post "list_found_products", to: "admins#list_found_products", as: "products_list"
        post "save_approved_products", to: "admins#save_approved_products", as: "products_save"

        # Searching for hot products by category
        get "hot_products_by_category", to: "admins#search_hot_products_by_category", as: "search_hot_products_by_category"
        post "hot_products_by_category", to: "admins#save_hot_products_by_category", as: "save_hot_products_by_category"

        # HACK: something is combined in these routes!
        # Search for all hot products/all not hot products in subcategories
        get "auto_save_hot_products", to: "admins#auto_hot_products", as: "save_hot_products_view"
        post "auto_save_hot_products", to: "admins#auto_hot_products", as: "save_hot_products"
        get "fill_all_subcategories", to: "admins#fill_all_subcategories", as: "fill_all_subcategories"

        # 4 - various clearing
        get "archive_expired_products", to: "admins#archive_expired_products", as: "archive_expired_products"
      end

      scope :scraping, as: :scraping do
        get "update_product_details", to: "admins#update_products_details", as: "update_products_details"
        get "fetch_categories", to: "admins#fetch_categories", as: "fetch_categories"
      end
    end

    get "delete_empty_reviews", to: "admins#delete_empty_reviews", as: "delete_empty_reviews"

    match "comments_manager", to: "admins#comments_manager", as: "comments_manager", via: [:get, :post]

    match "fill_category_from_file", to: "admins#fill_category_from_file", as: "fill_category_from_file", via: [:get, :post]

    # UNDONE: Article manager
    get "article_manage", to: "admins#article_manager", as: "article_manager"
  end

  # Error 404 path
  get "*path", to: "visitors#error404", as: "error" # error 404 page
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :subcategory
  belongs_to :category
  has_many :productLike

  scope :hot_products, -> { where(is_hot: "y") }
  scope :recommended_products, ->(product) { where(category_id: product).limit(12) }
  scope :all_from_brand, ->(product) { where("productTitle like ?", "%#{product.extract_product_brand}%").where(category_id: product.category_id) }
  scope :like_title, ->(title) { find_by("productTitle LIKE ?", title) }
  scope :delete_without_category, -> { where('category_id not in (?)', Category.pluck(:id).delete_all) }
  scope :expired_products, -> { where("validTime < '#{Time.zone.now.strftime('%Y-%m-%d')}'") }

  # Saving all products
  def self.new_product(products, category_id)
    return if products.size.zero?
    logger.info("We have found #{products.length} products")
    products.each do |product_hash|
      if !Product.exists?(productId: product_hash["productId"].to_s)
        a = product_hash["30daysCommission"]
        product_hash = product_hash.except("30daysCommission")
        product = Product.new(product_hash)
        product.salePrice = product_hash["salePrice"].slice(4..12)
        product.productTitle = ActionView::Base.full_sanitizer.sanitize(product_hash["productTitle"])
        product.originalPrice = product_hash["originalPrice"].slice(4..12)
        product.thirtydaysCommission = a
        product.is_approved = "n"
        product.category_id = category_id
        product.save!
      else
        # TODO: When product exists update it's attributes
        logger.info("Product Already Exists")
      end
    end
    logger.info("Products successfully saved!")
  end

  def self.clear_unwanted_products(products)
    products.update_all(is_approved: "y") unless products.nil?
    Product.all.limit(40).where.not(is_approved: "y").order("id desc").delete_all # Delete unselected products
  end

  # REVIEW: Consider deleting it and add subcategory argument to #new_product
  # method for mass saving products founded by crawler - works well for saving from file and iterating through the categories
  def self.save_hot_products(products, category_id, subcategory_id)
    fields = %w[productId productTitle productUrl imageUrl
                originalPrice salePrice discount evaluateScore
                commission commissionRate 30daysCommission volume
                packageType lotNum validTime storeName storeUrl]
    products.each do |i|
      if !Product.find_by(productId: i["productId"]).nil?
        logger.info("Product Already Exists")
      else
        details = AliexpressScraper.get_product_details(fields, i["productId"]) # gettig all details about product from hot product list
        if details["result"].nil?
          logger.info("We have not found any details about #{i['productTitle']}.")
        else
          details = details["result"]
          a = details["30daysCommission"]
          i = details.except("30daysCommission")
          promotion_link = AliexpressScraper.get_promotion_links(i["productUrl"])["result"]["promotionUrls"] # getting promotion url from aliexpress
          product = Product.new(i) # making new instance in Hot Products table
          product.salePrice = i["salePrice"].slice(4..12)
          product.originalPrice = i["originalPrice"].slice(4..12)
          product.promotionUrl = promotion_link[0]["promotionUrl"] # saving promotion url to record
          product.thirtydaysCommission = a # adding 30 days commission to record
          product.category_id = category_id
          product.subcategory_id = subcategory_id
          product.is_hot = "y"
          product.is_approved = "y"
          begin
            product.save
          rescue
            sleep 2
            ActiveRecord.connection.reconnect!
            retry
          end
        end
      end
    end
  end

  # Add product details
  def self.save_product_description(product_description, product_id)
    product = Product.find(product_id)
    product.update(productDescription: product_description)
  end

  def self.add_promotion_links(products)
    return if products.empty?
    promo_urls = AliexpressScraper.get_promotion_links(products.pluck(:productUrl))["result"]["promotionUrls"]
    i = 0
    products.each do |product|
      product.update(promotionUrl: promo_urls[i]["promotionUrl"])
      logger.info("Added to product #{product.id} promotion link: #{promo_urls[i]['promotionUrl']}")
      i += 1
    end
  end

  # Clear expired products
  def self.archive_expired_products
    Product.expired_products.update_all(archived: "y")
  end

  # HACK: Should sale price be equal to original price?
  def self.transform_price
    Product.where("salePrice like '%us%'").each do |product|
      product.salePrice = product.salePrice.slice(4..12)
      product.originalPrice = product.salePrice.slice(4.12)
      product.save
    end
  end

  # TODO
  def extract_product_brand
    #productTitle.split(" ")[0]
  end

end

app/controllers/products_controller.rb
# --------------------------------- NAVIGATION ------------------------------
# 1 - Basic CRUD actions
# 2 - Various Actions
# ------------------------------------ END ---------------------------------

class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :destroy, :product_like, :product_unlike]
  before_action :is_admin, only: [:create]

  # 1 - Basic CRUD Actions

  def index
    @categories = Category.all
    @categories ||= ["Sorry, actually no categories ;("]

    # META
    set_meta_tags title: "Find Cheapests Products"
    set_meta_tags description: "Are you looking for the cheapests aliexpress products? Here you can find products and also reviews of them!"
    set_meta_tags keywords: "aliexpress,category,products,deals,find,review,test"
  end

  def show
    @ali_reviews = AliReview.non_empty_reviews_of_product(@product)
    @product_reviews = Review.all_by_random
    @recommended_products = Product.recommended_products(@product.category_id)
    @best_products = Product.hot_products.limit(8) # limit must be %4=0!!
    @branded_products = Product.all_from_brand(@product) # limit%4==0
    @subcategory = Subcategory.find(@product.subcategory_id) if !@product.subcategory_id.nil? && @product.subcategory_id != @product.category_id

    # META
    set_meta_tags title: @product.productTitle.html_safe
    set_meta_tags description: @product.productDescription
    set_meta_tags keywords: @product.productTitle.split.join(",")
    set_meta_tags og: {
      image: @product.imageUrl
    }
    set_meta_tags twitter: {
      image: @product.imageUrl,
      title: @product.productTitle,
      description: "Only #{@product.salePrice}$ for this new product - check this out!"
    }
  end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # ---------------------------------- 1 - END --------------------------------

  # 2 - Various Actions

  # like box on product page, appears only on resolution >= 1080p
  def product_like
    if user_signed_in?
      ProductLike.create_like(@product.productId, current_user_columns.id, cookies[:user_id])
    else
      ProductLike.create_like(@product.productId, 4, cookies[:user_id])
    end
    render layout: false
  end

  def product_unlike
    ProductLike.destroy_like(@product.productId, cookies[:user_id])
    render layout: false
  end

  def import
    Product.import(params[:file])
    redirect_to root_url, notice: "Poducts imported."
  end

  def find_subcategory
    @subcategories = Subcategory.find_all_products_of_parent
  end

  def go_to_aliexpress
    @product = Product.where(productId: params[:id]).first
    redirect_to @product.promotionUrl
  end

  # -------------------------------- 2 - END ------------------------------

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.like_title(pretty_url_decode(params[:productTitle]))
    redirect_to error_path("product-not-found") if @product.nil?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params
      .require(:product)
      .permit(
        :totalResults, :productId, :productTitle, :productUrl,
        :imageUrl, :originalPrice, :salePrice, :discount,
        :evaluateScore, :thirtydaysCommission, :volume, :packageType,
        :lotNum, :validTime, :quanity_sold, :commision, :discount,
        :aff_url, :category, :subcategory, :sub_subcategory, :productDescription
      )
  end
end

# actually not used
def similar_product
  @product = Product.find_product(params[:productId])
  if @product.nil?
    fields = AliConfig.new.alibaba_api_fields[:list]
    category_id = Category.where(name: params[:category]).first.id
    @product = AliCrawler.new.get_product_details(fields, params[:productId])
    @product = Product.ali_new(@product["result"], category_id)
    @product = Product.where(productId: params[:productId]).first
  end
  redirect_to product_path(pretty_url_encode(@product.productTitle))
end

# PATCH/PUT /products/product title
def update
  respond_to do |format|
    if @product.update(product_params)
      format.html { redirect_to @product, notice: "Product was successfully updated." }
      format.json { render :show, status: :ok, location: @product }
    else
      format.html { render :edit }
      format.json { render json: @product.errors, status: :unprocessable_entity }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def select_progress_bar_class(index)
    case index
    when 1
      "progress-bar-danger"
    when 2
      "progress-bar-warning"
    when 3
      "progress-bar-info"
    when 4
      "progress-bar-primary"
    when 5
      "progress-bar-success"
    end
  end
end

app/views/products/_best_products.html.haml
- if products.count >= 4
  .container
    .col-md-12.col-xs-12
      .carousel.slide{"data-ride" => "carousel", :id => "myCarousel", :style => "width:100%;height:100%;"}
        .carousel-inner
          - $hot = 0
          - products.in_groups_of(4, false).each do |product_group|
            %div{ class: [ ("item active" if $hot == 0), ("item" if $hot != 0) ] }
              - $hot += 1
              - product_group.each do |product|
                %ul.thumbnails
                  %li.col-md-3.col-xs-12
                    .fff
                      .thumbnail
                        = link_to product_path(pretty_url_encode(product.productTitle)) do
                          = image_tag "#{product.imageUrl}_250x250.jpg"
                      .caption.text-center
                        %h4= pretty_url_decode(product.productTitle)
                        = link_to product_path(pretty_url_encode(product.productTitle)), class: "btn btn-success btn-sm", style: "margin:5px;" do
                          » Read More
          %nav
            %ul.control-box.pager
              %li
                %a.carousel-control-a{"data-slide" => "prev", :href => "#myCarousel", :role => "button"}
                  %i.glyphicon.glyphicon-chevron-left
              %li
                %a.carousel-control-a{"data-slide" => "prev", :href => "#myCarousel", :role => "button"}
                  %i.glyphicon.glyphicon-chevron-right

:javascript
  // Carousel Auto-Cycle
    $(document).ready(function() {
      $('.carousel').carousel({
        interval: 6000
      })
    });

app/views/products/_category_listing.html.haml
.container
  .row
    %h2 Find products by category:
    .col-md-12
      - @categories.each do |category|
        .col-lg-2.col-md-4.col-sm-6.col-xs-12
          .process
            .process-row
              .process-step
                = link_to search_category_products_path(category.name,1), class: "btn btn-default btn-circle category-listing-link" do
                  =icon('fa', "#{category.icon} fa-3x")
                %p= category.name

app/views/products/_recommend.html.haml
.container
  .row
    .col-md-4
      .product-item
        .pi-img-wrapper
          %img.img-responsive{:alt => "Berry Lace Dress", :src => "http://keenthemes.com/assets/bootsnipp/k1.jpg"}/
          %div
            %a.btn{:href => "#"} Zoom
            %a.btn{:href => "#"} View
        %h3
          %a{:href => "shop-item.html"} Berry Lace Dress
        .pi-price $29.00
        %a.btn.add2cart{:href => "javascript:;"} Add to cart
        .sticker.sticker-new
    .col-md-4
      .product-item
        .pi-img-wrapper
          %img.img-responsive{:alt => "Berry Lace Dress", :src => "http://keenthemes.com/assets/bootsnipp/k2.jpg"}/
          %div
            %a.btn{:href => "#"} Zoom
            %a.btn{:href => "#"} View
        %h3
          %a{:href => "shop-item.html"} Berry Lace Dress
        .pi-price $29.00
        %a.btn.add2cart{:href => "javascript:;"} Add to cart
    .col-md-4
      .product-item
        .pi-img-wrapper
          %img.img-responsive{:alt => "Berry Lace Dress", :src => "http://keenthemes.com/assets/bootsnipp/k3.jpg"}/
          %div
            %a.btn{:href => "#"} Zoom
            %a.btn{:href => "#"} View
        %h3
          %a{:href => "shop-item.html"} Berry Lace Dress
        .pi-price $29.00
        %a.btn.add2cart{:href => "javascript:;"} Add to cart
:css
  .product-item {
      padding: 15px;
      background: #fff;
      margin-top: 20px;
      position: relative;
  }
  .product-item:hover {
      box-shadow: 5px 5px rgba(234, 234, 234, 0.9);
  }
  .product-item:after {
      content: ".";
      display: block;
      height: 0;
      clear: both;
      visibility: hidden;
      font-size: 0;
      line-height:0;
  }
  .sticker {
      position: absolute;
      top: 0;
      left: 0;
      width: 63px;
      height: 63px;
  }
  .sticker-new {
      background: url(http://keenthemes.com/assets/bootsnipp/new.png) no-repeat;
      left: auto;
      right: 0;
  }
  .pi-img-wrapper {
      position: relative;
  }
  .pi-img-wrapper div {
      background: rgba(0,0,0,0.3);
      position: absolute;
      left: 0;
      top: 0;
      display: none;
      width: 100%;
      height: 100%;
      text-align: center;
  }
  .product-item:hover>.pi-img-wrapper>div {
      display: block;
  }
  .pi-img-wrapper div .btn {
      padding: 3px 10px;
      color: #fff;
      border: 1px #fff solid;
      margin: -13px 5px 0;
      background: transparent;
      text-transform: uppercase;
      position: relative;
      top: 50%;
      line-height: 1.4;
      font-size: 12px;
  }
  .product-item .btn:hover {
      background: #e84d1c;
      border-color: #c8c8c8;
  }
  
  .product-item h3 {
      font-size: 14px;
      font-weight: 300;
      padding-bottom: 4px;
      text-transform: uppercase;
  }
  .product-item h3 a {
      color: #3e4d5c;
  }
  .product-item h3 a:hover {
      color: #E02222;
  }
  .pi-price {
      color: #e84d1c;
      font-size: 18px;
      float: left;
      padding-top: 1px;
  }
  .product-item .add2cart {
      float: right;
      color: #a8aeb3;
      border: 1px #ededed solid;
      padding: 3px 6px;
      text-transform: uppercase;
  }
          .product-item .add2cart:hover {
              color: #fff;
              background: #e84d1c;
              border-color: #e84d1c;
          }







    - if @categories.nil?
      %h2{:style => "text-transform:uppercase;"}
        There is no more categories to show  - #{link_to "More products", products_path, style: "color:blue;"}
    - else
      - @categories.each do |category|
        - session[:excluded_categories] << category.id
        %h1
          %i{:class => "#{category.icon}"}
          = link_to category.name, search_category_products_path(category.name,1)
        - $category = Category.find(category.id).products
        - $rand = rand(0..$category.length-8)
        - $category[$rand...$rand+8].each do |product|
          - if $i%8 == 0
            .row
              - if $i%4 == 0
                .one-item.col-md-3.col-sm-3.col-xs-12
                  .item-sp.item-lg
                    %span{:itemscope => "", :itemtype => "http://schema.org/Product"}
                      = link_to product_path(pretty_url_encode(product.productTitle)), itemprop: "url" do
                        .thumb.vertical-alignment-helper
                          .vertical-align-center.vertical-align-top
                            = image_tag "#{product.imageUrl}_350x350.jpg", class: "img-responsive"
                        %h4{:itemprop => "name"}
                          = simple_format(pretty_url_decode(product.productTitle))
                        .price{:itemprop => "offers", :itemscope => "", :itemtype => "http://schema.org/Offer"}
                          %meta{:content => "#{product.salePrice}", :itemprop => "price"}/
                          %meta{:content => "USD", :itemprop => "priceCurrency"}/
                          %span.small NOW ONLY:
                          %span.big
                            US #{product.salePrice}$
                - $start = $start + 6
              - else
                - $end = $end + 2
                - if $start%6 == 0
                  .three-item.col-md-3.col-sm-3.col-xs-12
                    .item-sp.item-sm
                      %span{:itemscope => "", :itemtype => "http://schema.org/Product"}
                        = link_to product_path(pretty_url_encode(product.productTitle)), itemprop: "url" do
                          .thumb.vertical-alignment-helper
                            .vertical-align-center.vertical-align-top
                              = image_tag "#{product.imageUrl}_200x200.jpg", class: "img-responsive"
                          %h4{:itemprop => "name"}
                            = simple_format(pretty_url_decode(product.productTitle))
                          %meta{:content => "4.8", :itemtype => "http://schema.org/AggregateRating/ratingValue"}/
                          %meta{:content => "5.0", :itemtype => "http://schema.org/AggregateRating/reviewCount"}/
                          .price{:itemprop => "offers", :itemscope => "", :itemtype => "http://schema.org/Offer"}
                            %meta{:content => "#{product.salePrice}", :itemprop => "price"}/
                            %meta{:content => "USD", :itemprop => "priceCurrency"}/
                            %span.small NOW ONLY:
                            %span.big
                              = product.salePrice
                              $
                    - $start = $start + 2
                    - if $start%12 == 0
              - $i = $i + 1
              - if $i%8==0
        %hr{:style => "background-color:#{random_colors};height:5px;border-radius:5px 5px 5px 5px;"}/
  .rounded-plus-container
    = link_to new_products_append_path, remote: true, style: "width:180px;height:180px;", class: "add-categories" do
      .rounded-plus
        = icon('fa', 'plus fa-5x')


:javascript
  $(function() {
    $('.add-categories').click(function() {
      $('.rounded-plus-container').fadeOut(200);
    });
  });

app/views/products/_recommended_products.html.haml
- $hot=0
.container
  .col-md-12.col-xs-12
    #myCarousel.carousel.slide.best
      .carousel-inner
        .item.active
          %ul.thumbnails
            - @best_products.each do |product|
              %li.col-md-3.col-xs-12
                .fff
                  .thumbnail
                    - $category = Category.where(id: @product.category).first
                    = link_to add_similar_product_path($category.name, pretty_url_encode(product['productTitle']), product['productId']) do
                      = image_tag "#{product['imageUrl']}_250x250.jpg"
                  .caption.text-center
                    %h4= simple_format(pretty_url_decode(product['productTitle']))
                    = link_to add_similar_product_path($category.name, pretty_url_encode(product['productTitle']), product['productId']), |
                      class: "btn btn-success btn-sm", style: "margin:5px;" do                                                            |
                      » Read More
              - $hot = $hot + 1
              - if $hot%4==0
                - if $hot==@best_products.length
        - else
      / /Slide
      .item
        %ul.thumbnails
      / /#myCarousel
      %nav
        %ul.control-box.pager
          %li
            %a.carousel-control-a{"data-slide" => "prev", :href => "#myCarousel"}
              %i.glyphicon.glyphicon-chevron-left
          %li
            %a.carousel-control-a{"data-slide" => "next", :href => "#myCarousel"}
              %i.glyphicon.glyphicon-chevron-right
    / /.carousel-slide
  / /.col-xs-12
/ /.row
:javascript
  // Carousel Auto-Cycle
    $(document).ready(function() {
      $('.carousel').carousel({
        interval: 6000
      })
    });

app/views/products/_subcategories.html.haml
= f.collection_select(:subcategory, Subcategory.select(@subcategories), :id, :name, class: "form-control")

app/views/products/edit.html.haml
.page-header
  = link_to products_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @product, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing product
= render 'form'

app/views/products/get_subcategory.js.haml
$('#item_subcategory').empty();
- @subcategories.each do |subcategory|
  $('#item_subcategory').append($('
  %option{:value => "#{subcategory.id}"}>= subcategory.name
  '));

app/views/products/new.html.haml
.page-header
  = link_to products_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New product
= render 'form'

app/views/products/save_hot_products.html.haml
= @products

app/views/products/show.html.haml
- url = Rails.application.routes.recognize_path(request.referrer)
- if url[:action] != "search_category"
  - if !@product.subcategory_id.nil? && @product.subcategory_id != @product.category_id
    = link_to "Home", root_path
    \-&gt; #{link_to Category.find(@product.category_id).name, products_category_search_path(Category.find(@product.category_id).name,1)}
    \ -&gt;
    \#{link_to @subcategory.name, subcategory_category_search_path(Category.find(@product.category_id).name,@subcategory.name,1)} 
    \-&gt;
    \#{@product.productTitle.slice(0..40)}...
  - else
    = link_to "Home", root_path
    \-&gt; 
    \#{link_to Category.find(@product.category_id).name, products_category_search_path(Category.find(@product.category_id).name,1)}
    \ -&gt; #{@product.productTitle.slice(0..40)}...
- else
  = link_to "Home", root_path
  \-&gt; #{link_to "Back", request.referrer} -&gt; #{@product.productTitle.slice(0..40)}...
.container-fluid
  .content-wrapper
    .item-container
      .container
        .col-md-12
          .product.col-md-5.col-xs-12.service-image-left{:style => "height:100%;"}
            %center
              = image_tag @product.imageUrl, class: "product-display"
          .col-md-7
            .product-title
              = simple_format(@product.productTitle)
            .product-rating
              = render "/products/show/rating", reviews: @ali_reviews, rating: AliReview.calculate_product_rating(@ali_reviews)
            %hr/
            .product-price
              = @product.salePrice
              $ / #{@product.packageType}
              - if @product.archived == "y"
                =icon('fas', 'exclamation-triangle', style: "color:red")
                Price may be outdated
              - else
                =icon('fas', 'exclamation-triangle', style: "color:green")
                Price up to date
            .product-stock In Stock
            %hr
            = link_to @product.promotionUrl do
              .btn-group.cart
                = link_to aliexpress_pretty_url_path(@product.productId), target: "_blank" do
                  %button.btn.btn-success{:type => "button"}
                    Buy Now
            .btn-group.wishlist
              %button.btn.btn-danger{:type => "button"}
                Add To Cart
        = render "/layouts/ad"
        = render "/products/show/user_feedback"
    .container-fluid
      .col-md-12.product-info
        %ul#myTab.nav.nav-tabs.nav_tabs
          - if @ali_reviews.length > 0
            %li.active
              %a{"data-toggle" => "tab", :href => "#reviews"} REVIEWS
            %li
              %a{"data-toggle" => "tab", :href => "#product-info"} PRODUCT INFO
          - else
            %li.active
              %a{"data-toggle" => "tab", :href => "#product-info"} PRODUCT INFO
            %li
              %a{"data-toggle" => "tab", :href => "#reviews"} REVIEWS
        #myTabContent.tab-content
          %div{ id: 'product-info', class: [ ('tab-pane fade in' if @ali_reviews.length > 0), ('tabe-pane  fade in active' if @ali_reviews.length <= 0) ] }
            %section.col-xs-12.container.product-info.text-center
              = print_multiline(@product.productDescription) unless @product.productDescription.nil?
              - if @product.productDescription.nil?
                We are working on gathering details of this product!

          %div{ id: "reviews", class: [ ("tab-pane fade in" if @ali_reviews.length == 0), ("tab-pane fade in active" if @ali_reviews.length > 0) ] }
            %container
              = render "/products/show/call_to_action"
              - i = 0
              - if @ali_reviews.length > 0
                - @ali_reviews.each do |review|
                  = render "/products/show/aliexpress_reviews", review: review, i: i
                  - i = i + 1
                  
        %hr
    = render "best_products", products: @branded_products[0..-((@branded_products.length % 4) + 1)]
    - $brand = ActionView::Base.full_sanitizer.sanitize("AliBestDeal - No Description").split(" ")
    - $description = $brand
    - $index = $brand.index("Name:")
    %script{:type => "application/ld+json"}
      :cdata
        {
        "@context": "http://schema.org/",
        "@type": "Product",
        "name": "#{@product.productTitle}",
        "brand": "#{if $index != nil then $brand[$index+1] else $brand = "Unknow" end}",
        "image": "#{@product.imageUrl}",
        "description": "#{$description.join(" ")[0..117]}...",
        "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "#{@rate}",
        "ratingCount": "#{@rate_count}"
        },
        "offers": {
        "@type": "Offer",
        "priceCurrency": "USD",
        "price": "#{@product.salePrice}",
        "priceValidUntil": "#{@product.validTime}",
        "itemCondition": "http://schema.org/NewCondition",
        "availability": "http://schema.org/InStock",
        "seller": {
        "@type": "Organization",
        "name": "Aliexpress"
        }
        }
        }